// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqUitQMDUOB4f3iY1_OEiDZhJy039a6yc',
    appId: '1:674244004136:web:423d282192bf0480fe681d',
    messagingSenderId: '674244004136',
    projectId: 'backend-golang-46fd8',
    authDomain: 'backend-golang-46fd8.firebaseapp.com',
    storageBucket: 'backend-golang-46fd8.firebasestorage.app',
    measurementId: 'G-JXMPQT94SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRu15owhGYb56gCEhKGkb84lpjq3P_5j4',
    appId: '1:674244004136:android:9c6977b72d05462ffe681d',
    messagingSenderId: '674244004136',
    projectId: 'backend-golang-46fd8',
    storageBucket: 'backend-golang-46fd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVB9ulLYx6wlcMDXzkEzEo-RHlA2VaVXg',
    appId: '1:674244004136:ios:508851cc87b367c4fe681d',
    messagingSenderId: '674244004136',
    projectId: 'backend-golang-46fd8',
    storageBucket: 'backend-golang-46fd8.firebasestorage.app',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVB9ulLYx6wlcMDXzkEzEo-RHlA2VaVXg',
    appId: '1:674244004136:ios:508851cc87b367c4fe681d',
    messagingSenderId: '674244004136',
    projectId: 'backend-golang-46fd8',
    storageBucket: 'backend-golang-46fd8.firebasestorage.app',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqUitQMDUOB4f3iY1_OEiDZhJy039a6yc',
    appId: '1:674244004136:web:7fd13d033ea4fb0cfe681d',
    messagingSenderId: '674244004136',
    projectId: 'backend-golang-46fd8',
    authDomain: 'backend-golang-46fd8.firebaseapp.com',
    storageBucket: 'backend-golang-46fd8.firebasestorage.app',
    measurementId: 'G-QLC2HMT6SZ',
  );
}
